raise Exception.new( "This is an expected error" )
